version: '3'
services:
  api:
    container_name: api
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  database:
    container_name: my-postgres-db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    volumes:
      - ./api/pData:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
  frontend-dev:
    container_name: frontend-dev
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - api
    links:
      - api